# Fingers Crossed ....
version: "3.2"
services:
  app-nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: app-nginx
    volumes:
      - ../application:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app-php-fpm
    expose:
      - "8180"
    ports:
      - "80:8180"
    networks:
      app-network:
        ipv4_address: "172.18.0.88"
    tty: true
    env_file:
      - '.env'

  app-php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: app-php-fpm
    volumes:
      - ../application:/var/www/app
    links:
      - app-mysql
    networks:
      app-network:
        ipv4_address: "172.18.0.2"
    env_file:
      - '.env'

  app-mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: app-mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      app-network:
        ipv4_address: "172.18.0.3"
    env_file:
      - '.env'

volumes:
  mysql_data:
    external: true
networks:
  app-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

